version: '3.8'

services:
  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://dev:dev@db:5432/dev
    depends_on:
      - db

  db:
    image: postgres:12.14@sha256:38dd973e62efcf05026918c597ff337c6afda6f4b63f2d9e642df4189a5db78c
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev

volumes:
  postgres_data:
