skip-check:
  - CKV2_AWS_5:  # Ensure that Security Groups are attached to another resource
  - CKV2_AWS_31: # Ensure WAF2 has a Logging Configuration
  - CKV2_AWS_38: # Ensure Domain Name System Security Extensions (DNSSEC) signing is enabled for Amazon Route 53 public hosted zones
  - CKV2_AWS_39: # Ensure Domain Name System (DNS) query logging is enabled for Amazon Route 53 hosted zones
  - CKV2_AWS_47: # Ensure AWS CloudFront attached WAFv2 WebACL is configured with AMR for Log4j Vulnerability
  - CKV_AWS_51:  # Ensure ECR Image Tags are immutable
  - CKV_AWS_86:  # Ensure Cloudfront distribution has Access Logging enabled
  - CKV_AWS_136: # Ensure that ECR repositories are encrypted using KMS
  - CKV_AWS_192: # Ensure WAF prevents message lookup in Log4j2. See CVE-2021-44228 aka log4jshell
  - CKV_AWS_258  # Ensure that Lambda function URLs AuthType is not None
