skip-check:
  - CKV2_AWS_5  # Security Groups: False positive, this is attached to the lambda 
  - CKV2_AWS_31 # WAF: WAF logging is not required
  - CKV2_AWS_32 # CloudFront: False-positive, strict header security policy is being applied 
  - CKV2_AWS_38 # Route53: DNS Secruity Extensions (DNSSEC) signing not required 
  - CKV2_AWS_39 # Route53: False positive, we have DNS query logging but checkov cant see it
  - CKV2_AWS_47 # Cloudfront: No Log4j dependency and false positive, AWSManagedRulesKnownBadInputsRuleSet is being applied
  - CKV_AWS_51  # ECR: `latest` tag is used for development 
  - CKV_AWS_86  # CloudFront: Access logging not required
  - CKV_AWS_119 # DynamoDB default service key encryption is acceptable
  - CKV_AWS_136 # ECR: Default encryption key is acceptable 
  - CKV_AWS_192 # CloudFront: False-positive, AWSManagedRulesKnownBadInputsRuleSet is being applied 
  - CKV_AWS_258 # Lambda: Lambda function url auth is handled at the API level 
