version: '3.8'

services:
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest@sha256:bd10279256d657b3637862ab813b3b7f1c3438395ac318ccd99b62c17f35d2d3"
    container_name: dynamodb-local
    ports:
      - "9000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.11"
        NODE_VERSION: "none"
    environment:
      ALLOWED_DOMAINS: 'canada.ca,gc.ca,cds-snc.ca'
      AUTH_TOKEN_APP: 'auth_token_app'
      AUTH_TOKEN_NOTIFY: 'auth_token_notify'
      AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
      AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
      AWS_REGION: 'ca-central-1'
      CLOUDFRONT_HEADER: 'localhost'
      DOCS_URL: '/docs'
      DYNAMO_ENDPOINT: 'http://db:8000'
      DYNAMODB_HOST: 'http://db:8000'
      LOGIN_TOKEN_SALT: 'jesuisunsel'
      SHORTENER_DOMAIN: 'http://127.0.0.1:8000/'
      SHORTENER_PATH_LENGTH: '8'
      PEPPERS: 'ejp8zh0QHl1BKPMvH4d9zFvS1rkbnYz9uqaEae9uwmY=,fwNAF1u7dA3j0YtsOoHtE0wIzCisSyzqTOhI4TkG5dA=,W2ktstHWiB1+UJLku8Mi0f1Su5RhX+p7hx7UxsrNVOE=,QIPgZU1zZ/tdLAigsLPl4j1zQ8Yc2rUMrVrSMTnZwlM=,sUUmk4x4tgVvfAxM9cu/ZCeIL88SJefJYFkZcHERYEY='

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

