FROM cypress/included:12.17.4@sha256:102b34b9e4cb9895c44a74293c6931e7282535775045dd8b1c7608667a34c4b6

# install dependencies
ENV NODE_PATH=/usr/local/lib/node_modules
RUN yarn add cypress-axe axe-core cypress-wait-for-stable-dom