FROM cypress/included:12.17.3@sha256:21d0a26cc64d046f7a5adde56ea5f7e84b7981000da3466b9671a3393f085566

# install dependencies
ENV NODE_PATH=/usr/local/lib/node_modules
RUN yarn add cypress-axe axe-core cypress-wait-for-stable-dom