FROM cypress/included:12.10.0@sha256:67c2db9f4dc28a92bd11e2244d29b3d351fc737edf90703b6c9dd4ae9137d89b 

# install dependencies
ENV NODE_PATH=/usr/local/lib/node_modules
RUN yarn add cypress-axe axe-core cypress-wait-for-stable-dom