"""Change db fields

Revision ID: 7b8815d2136e
Revises: e18cd97d4269
Create Date: 2022-04-01 21:02:03.964345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b8815d2136e"
down_revision = "e18cd97d4269"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_allowed_domains_domain"), "allowed_domains", ["domain"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_allowed_domains_domain"), table_name="allowed_domains")
    # ### end Alembic commands ###
