"""create allowed_domains tabled

Revision ID: e18cd97d4269
Revises: cd33c5fd06d2
Create Date: 2022-03-19 15:18:40.013031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e18cd97d4269'
down_revision = 'cd33c5fd06d2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_domains',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
 # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allowed_domains')
    # ### end Alembic commands ###
