ARG BASE_IMAGE="python:3.11.2-alpine3.16@sha256:8ef4d2faa319adb45b3e0c73c506d94db6b94367cccb8178e11a968c8fdc63d3"
FROM ${BASE_IMAGE} as builder

ARG RIE_VERSION="v1.10"

RUN apk add --no-cache \
    autoconf \
    automake \
    build-base \
    gcc \
    libc-dev \
    libcurl \
    libexecinfo-dev \
    libstdc++ \
    libtool \
    linux-headers \
    make \
    cmake \
    python3-dev \
    wget

RUN wget https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/download/${RIE_VERSION}/aws-lambda-rie

RUN mkdir -p /pymodules \
    && pip3 install awslambdaric --target /pymodules

COPY ./requirements.txt /
RUN pip3 install -r /requirements.txt --target /pymodules

# Lambda API image
FROM ${BASE_IMAGE} as lambda

COPY --from=builder /pymodules /pymodules
COPY --from=builder /aws-lambda-rie /usr/bin/aws-lambda-rie

# Build variables
ARG FUNCTION_DIR="/function"
ARG GIT_SHA
ENV GIT_SHA=$GIT_SHA
ENV PYTHONPATH="/pymodules"

RUN apk upgrade --no-cache \
    && apk add --no-cache \
    aws-cli \
    binutils \
    libstdc++

COPY bin/entry.sh /
RUN chmod 555 /usr/bin/aws-lambda-rie /entry.sh

# Copy function code
WORKDIR ${FUNCTION_DIR}
COPY . ${FUNCTION_DIR}

ENTRYPOINT [ "/entry.sh", "main.handler" ]
