name: Docker build and push to production

on:
  push:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: 806721586252.dkr.ecr.ca-central-1.amazonaws.com/url-shortener
  AWS_REGION: ca-central-1  

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@5727f247b64f324ec403ac56ae05e220fd02b65f # v2.1.0
        with:
          role-to-assume: arn:aws:iam::806721586252:role/url-shortener-apply
          role-session-name: ECRPush
          aws-region: ca-central-1

      - name: Build image
        working-directory: ./api
        run: |
          docker build \
            --build-arg GIT_SHA=$GITHUB_SHA \
            -t $REGISTRY/api:$GITHUB_SHA .

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@2f9f10ea3fa2eed41ac443fee8bfbd059af2d0a4 # v1.6.0

      - name: Push image to ECR
        run: |
          docker push $REGISTRY/api:$GITHUB_SHA

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
