name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**
      - .github/workflows/ci_code.yml

env:
  TERRAGRUNT_VERSION: v0.31.1

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: "amazon/dynamodb-local@sha256:c8702bde709520b90930c20ee430d4123cd731da8e544cc4ccae0e2a78ee4fce"
        ports:
          - 9000:8000

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        working-directory: ./api
        run: make install-dev

      - name: Install dependencies
        working-directory: ./api
        run: make install

      - name: Lint
        working-directory: ./api
        run: make lint-ci

      - name: Format
        working-directory: ./api
        run: make fmt-ci

      - name: Test
        working-directory: ./api
        run: make test
        env:
          AWS_ACCESS_KEY_ID: "AWSACCESSKEYID"
          AWS_SECRET_ACCESS_KEY: "AWSSECRETACCESSKEY"
          AWS_REGION: "ca-central-1"
          DYNAMODB_HOST: "http://localhost:9000"
