name: Cypress E2E tests
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**
      - .github/workflows/cypress_e2e.yml

env:
  TERRAGRUNT_VERSION: v0.31.1

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: "amazon/dynamodb-local"
        ports:
          - 9000:8000

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        working-directory: ./api
        run: make install-dev

      - name: Install dependencies
        working-directory: ./api
        run: make install

      - name: Start test server and run Cypress tests
        working-directory: ./api
        run: |
          nohup make e2e-dev &
          make e2e
        env:
          ALLOWED_DOMAINS: "canada.ca,gc.ca"
          AUTH_TOKEN_APP: "auth_token_app"
          AUTH_TOKEN_NOTIFY: "auth_token_notify"
          AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
          AWS_REGION: "ca-central-1"
          DYNAMODB_HOST: "http://localhost:9000"
          NOTIFY_API_KEY: ""
          NOTIFY_MAGIC_LINK_TEMPLATE: ""
          SHORTENER_DOMAIN: "http://127.0.0.1:8000/"
          TABLE_NAME: "url_shortener_test"
