name: Cypress E2E tests
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**
      - .github/workflows/cypress_e2e.yml

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: "amazon/dynamodb-local@sha256:c8702bde709520b90930c20ee430d4123cd731da8e544cc4ccae0e2a78ee4fce"
        ports:
          - 9000:8000

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.11"

      - name: Create DB
        run: |
          aws dynamodb create-table \
            --table-name url_shortener \
            --attribute-definitions AttributeName=key_id,AttributeType=S AttributeName=email,AttributeType=S \
            --key-schema AttributeName=key_id,KeyType=HASH \
            --global-secondary-indexes IndexName=emailIndex,KeySchema=["{AttributeName=email,KeyType=HASH}"],Projection="{ProjectionType=ALL}",ProvisionedThroughput="{ReadCapacityUnits=1,WriteCapacityUnits=1}" \
            --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
            --endpoint-url http://localhost:9000 \
            --no-cli-pager \
        env:
          AWS_ACCESS_KEY_ID: 'AWSACCESSKEYID'
          AWS_SECRET_ACCESS_KEY: 'AWSSECRETACCESSKEY'
          AWS_REGION: 'ca-central-1'

      - name: Install dev dependencies
        working-directory: ./api
        run: make install-dev

      - name: Install dependencies
        working-directory: ./api
        run: make install

      - name: Start test server and run Cypress tests
        working-directory: ./api
        run: |
          nohup make e2e-dev &
          make e2e-ci
        env:
          ALLOWED_EMAIL_DOMAINS: "canada.ca,gc.ca"
          ALLOWED_SHORTENED_DOMAINS: "canada.ca,gc.ca"
          AUTH_TOKEN_APP: "auth_token_app"
          AUTH_TOKEN_NOTIFY: "auth_token_notify"
          AWS_ACCESS_KEY_ID: "AWSACCESSKEYID"
          AWS_SECRET_ACCESS_KEY: "AWSSECRETACCESSKEY"
          AWS_REGION: "ca-central-1"
          CLOUDFRONT_HEADER: "localhost"
          DYNAMODB_HOST: "http://localhost:9000"
          LOGIN_TOKEN_SALT: "je_suis_un_sel"
          NOTIFY_API_KEY: ""
          NOTIFY_CONTACT_EMAIL: ""
          NOTIFY_CONTACT_TEMPLATE: ""
          NOTIFY_MAGIC_LINK_TEMPLATE: ""
          SHORTENER_DOMAIN: "http://127.0.0.1:8000/"
          SHORTENER_PATH_LENGTH: "6"