name: DAST vulnerability scan

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Docker build and push to staging"
      - "Deploy API to production"
    types:
      - completed

jobs:
  dast-vulnerability-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - url: 'https://url-shortener.cdssandbox.xyz'
          - url: 'https://o.alpha.canada.ca'
    
    steps:
      - name: Run Dastardly
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: '${{ matrix.url }}'

      - name: Publish report
        if: always()
        uses: mikepenz/action-junit-report@baaeba622e27b396105f35ec9ec4ee89ffcbd306 # v3.7.8
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true
