name: Deploy API to production

on:
  push:
    branches:
      - main
    paths:
      - .github/manifests/lambda_api_version

env:
  AWS_REGION: ca-central-1
  FUNCTION_NAME: url-shortener-api
  REGISTRY: 806721586252.dkr.ecr.ca-central-1.amazonaws.com/url-shortener

permissions:
  id-token: write
  contents: read

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@5727f247b64f324ec403ac56ae05e220fd02b65f # v2.1.0
        with:
          role-to-assume: arn:aws:iam::806721586252:role/url-shortener-apply
          role-session-name: DeployAPI
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy lambda
        run: |
          VERSION="$(cat .github/manifests/lambda_api_version)"
          aws lambda update-function-code \
            --function-name ${{ env.FUNCTION_NAME }} \
            --image-uri $REGISTRY/api:$VERSION  > /dev/null 2>&1

      - name: Publish new lambda version
        run: |
            aws lambda wait function-updated --function-name ${{ env.FUNCTION_NAME }}
            echo "VERSION=$(aws lambda publish-version --function-name ${{ env.FUNCTION_NAME }} | jq -r '.Version')" >> $GITHUB_ENV

      - name: Shift lambda traffic over 4 minutes
        uses: cds-snc/aws-lambda-traffic-shifting-action@6b134de1b3404f6c12331f5cf25904671228a960 # 0.4
        env:
            ALIAS: latest
            FUNCTION_NAME: ${{ env.FUNCTION_NAME }}
            GREEN_VERSION: ${{ env.VERSION }}
            ROLLOUT_STEPS: 4
            ROLLOUT_TIME_IN_MINUTES: 4

      - name: CloudFront cache invalidate
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_CLOUDFRONT_DIST_ID }} --paths "/*"

      - name: API healthcheck
        uses: jtalk/url-health-check-action@61a0e49fff5cde3773b0bbe069d4ebbd04d24f07 # tag=v2
        with:
          url: https://o.alpha.canada.ca/version
          max-attempts: 3
          retry-delay: 5s
