name: Load testing
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**
      - .github/workflows/loadtesting.yml

jobs:
  load_testing:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: "amazon/dynamodb-local@sha256:c8702bde709520b90930c20ee430d4123cd731da8e544cc4ccae0e2a78ee4fce"
        ports:
          - 9000:8000

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.11"

      - name: Create DB
        run: |
          aws dynamodb create-table \
            --table-name url_shortener \
            --attribute-definitions AttributeName=key_id,AttributeType=S AttributeName=email,AttributeType=S \
            --key-schema AttributeName=key_id,KeyType=HASH \
            --global-secondary-indexes IndexName=emailIndex,KeySchema=["{AttributeName=email,KeyType=HASH}"],Projection="{ProjectionType=ALL}",ProvisionedThroughput="{ReadCapacityUnits=1,WriteCapacityUnits=1}" \
            --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
            --endpoint-url http://localhost:9000 \
            --no-cli-pager \
        env:
          AWS_ACCESS_KEY_ID: 'AWSACCESSKEYID'
          AWS_SECRET_ACCESS_KEY: 'AWSSECRETACCESSKEY'
          AWS_REGION: 'ca-central-1'


      - name: Install dev dependencies
        working-directory: ./api
        run: make install-dev

      - name: Install dependencies
        working-directory: ./api
        run: make install

      - name: Download k6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.43.1/k6-v0.43.1-linux-amd64.tar.gz -o k6.tar.gz
          tar -xzf k6.tar.gz
          sudo mv k6-*/k6 /usr/local/bin

      - name: Run load testing
        working-directory: ./api
        run: |
          nohup make e2e-dev &
          sleep 5
          make loadtest
        env:
          ALLOWED_EMAIL_DOMAINS: "canada.ca,gc.ca"
          ALLOWED_SHORTENED_DOMAINS: "canada.ca,gc.ca"
          AUTH_TOKEN_APP: "auth_token_app"
          AUTH_TOKEN_NOTIFY: "auth_token_notify"
          AWS_ACCESS_KEY_ID: "AWSACCESSKEYID"
          AWS_SECRET_ACCESS_KEY: "AWSSECRETACCESSKEY"
          AWS_REGION: "ca-central-1"
          CLOUDFRONT_HEADER: "localhost"
          DYNAMODB_HOST: "http://localhost:9000"
          ENV: "ci"
          LOGIN_TOKEN_SALT: "je_suis_un_sel"
          NOTIFY_API_KEY: ""
          NOTIFY_CONTACT_EMAIL: ""
          NOTIFY_CONTACT_TEMPLATE: ""
          NOTIFY_MAGIC_LINK_TEMPLATE: ""
          PEPPERS: 'ejp8zh0QHl1BKPMvH4d9zFvS1rkbnYz9uqaEae9uwmY=,fwNAF1u7dA3j0YtsOoHtE0wIzCisSyzqTOhI4TkG5dA=,W2ktstHWiB1+UJLku8Mi0f1Su5RhX+p7hx7UxsrNVOE=,QIPgZU1zZ/tdLAigsLPl4j1zQ8Yc2rUMrVrSMTnZwlM=,sUUmk4x4tgVvfAxM9cu/ZCeIL88SJefJYFkZcHERYEY='
          SHORTENER_DOMAIN: "http://127.0.0.1:8000/"
          SHORTENER_PATH_LENGTH: "8"
