name: Load testing
on:
  workflow_dispatch:
  pull_request:
    paths:
      - api/**
      - .github/workflows/loadtesting.yml

jobs:
  load_testing:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: "amazon/dynamodb-local"
        ports:
          - 9000:8000

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.11"

      - name: Create DB
        run: |
          aws dynamodb create-table \
            --table-name url_shortener \
            --attribute-definitions AttributeName=key_id,AttributeType=S AttributeName=email,AttributeType=S \
            --key-schema AttributeName=key_id,KeyType=HASH \
            --global-secondary-indexes IndexName=emailIndex,KeySchema=["{AttributeName=email,KeyType=HASH}"],Projection="{ProjectionType=ALL}",ProvisionedThroughput="{ReadCapacityUnits=1,WriteCapacityUnits=1}" \
            --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
            --endpoint-url http://localhost:9000 \
            --no-cli-pager \
        env:
          AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
          AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
          AWS_REGION: 'ca-central-1'
     

      - name: Install dev dependencies
        working-directory: ./api
        run: make install-dev

      - name: Install dependencies
        working-directory: ./api
        run: make install

      - name: Download k6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.43.1/k6-v0.43.1-linux-amd64.tar.gz -o k6.tar.gz
          tar -xzf k6.tar.gz
          sudo mv k6-*/k6 /usr/local/bin

      - name: Run load testing
        working-directory: ./api
        run: |
          nohup make e2e-dev &
          sleep 5
          make loadtest
        env:
          ALLOWED_DOMAINS: "canada.ca,gc.ca"
          AUTH_TOKEN_APP: "auth_token_app"
          AUTH_TOKEN_NOTIFY: "auth_token_notify"
          AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
          AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
          AWS_REGION: "ca-central-1"
          DYNAMODB_HOST: "http://localhost:9000"
          ENVIRONMENT: "ci"
          NOTIFY_API_KEY: ""
          NOTIFY_MAGIC_LINK_TEMPLATE: ""
          PEPPERS: 'ejp8zh0QHl1BKPMvH4d9zFvS1rkbnYz9uqaEae9uwmY=,fwNAF1u7dA3j0YtsOoHtE0wIzCisSyzqTOhI4TkG5dA=,W2ktstHWiB1+UJLku8Mi0f1Su5RhX+p7hx7UxsrNVOE=,QIPgZU1zZ/tdLAigsLPl4j1zQ8Yc2rUMrVrSMTnZwlM=,sUUmk4x4tgVvfAxM9cu/ZCeIL88SJefJYFkZcHERYEY='
          SHORTENER_DOMAIN: "http://127.0.0.1:8000/"
          SHORTENER_PATH_LENGTH: "8"
