name: Smoke test
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Docker build and push to staging"
      - "Deploy API to production"    
  schedule:
    - cron: "0 3 * * *"
  pull_request:
    paths:
      - .github/workflows/smoke_test.yml

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - url: 'https://url-shortener.cdssandbox.xyz'
            auth_token: 'STAGING_AUTH_TOKEN_APP'
          - url: 'https://o.alpha.canada.ca'
            auth_token: 'PROD_AUTH_TOKEN_APP'  
    steps:
      - name: Smoke test
        run: |
          response=$(curl -X POST ${{ matrix.url }}/v1 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets[matrix.auth_token] }}" \
            -d "{\"original_url\": \"https://digital.canada.ca?time=`date +%s`\"}" | jq -r '.short_url')

          if curl -s $response | grep -q "https://digital.canada.ca"; then
              echo "🎉 Smoke test passed"
          else
              echo "💩 Smoke test failed"
              exit 1
          fi
