name: "Terraform plan production"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/manifests/infrastructure_version"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.3.7
  TERRAGRUNT_VERSION: 0.40.2
  TF_VAR_auth_token_app: ${{ secrets.PROD_AUTH_TOKEN_APP }}
  TF_VAR_auth_token_notify: ${{ secrets.PROD_AUTH_TOKEN_NOTIFY }}
  TF_VAR_cloudfront_header: ${{ secrets.PROD_CLOUDFRONT_HEADER }}
  TF_VAR_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL_PROD }}
  TF_VAR_hashing_peppers: ${{ secrets.PROD_HASHING_PEPPERS }}
  TF_VAR_login_token_salt: ${{ secrets.PROD_LOGIN_TOKEN_SALT }}
  TF_VAR_notify_api_key: ${{ secrets.PROD_NOTIFY_API_KEY }}
  TF_VAR_notify_contact_email: ${{ secrets.PROD_NOTIFY_CONTACT_EMAIL }}
  TF_VAR_sentinel_customer_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  TF_VAR_sentinel_shared_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: hosted_zone
          - module: network
          - module: ecr
          - module: dynamodb
          - module: api
          - module: cloudfront 
          - module: alarms 
          - module: backup_plan 
          - module: conformance_pack 

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Get infrastructure version
        run: echo "INFRASTRUCTURE_VERSION=$(cat .github/manifests/infrastructure_version)" >> $GITHUB_ENV

      - name: Checkout infrastructure version tag
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ env.INFRASTRUCTURE_VERSION }}

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@5727f247b64f324ec403ac56ae05e220fd02b65f # v2.1.0
        with:
          role-to-assume: arn:aws:iam::806721586252:role/url-shortener-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@7f4ce4a4bdffaba639d32a45272804e37a569408 # v3.0.6
        with:
          comment-delete: true
          comment-title: "Production: ${{ matrix.module }}"
          directory: ./terragrunt/env/production/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
