name: Workflow failure

on:
  workflow_run:
    workflows:
      - "Deploy API to production"
      - "Docker build and push to production"
      - "Docker build and push to staging"
      - "Smoke test"
      - "Terraform apply production"
      - "Terraform apply staging"
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Notify Slack
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: GitHub workflow failed: <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow.name }}>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_PRODUCT_CHANNEL }}